dist: trusty
language: c++
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - boost1.67
    - g++-4.9

before_install:
  - cmake .
  - make -j

script:
  - ./geometry-tests

compiler:
  - gcc

os:
- linux